; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30140.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG90714 DB	'cmd.exe /c echo YOU HAVE BEEN HACKED > HACKED.txt', 00H
CONST	ENDS
PUBLIC	main
EXTRN	__imp_WinExec:PROC
pdata	SEGMENT
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+29
	DD	imagerel $unwind$main
pdata	ENDS
xdata	SEGMENT
$unwind$main DD	010401H
	DD	04204H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
main	PROC
; File C:\Users\Shayan Jadoon\source\repos\Project8\Project8\Source.cpp
; Line 4
$LN3:
	sub	rsp, 40					; 00000028H
; Line 5
	mov	edx, 1
	lea	rcx, OFFSET FLAT:$SG90714
	call	QWORD PTR __imp_WinExec
; Line 6
	xor	eax, eax
; Line 7
	add	rsp, 40					; 00000028H
	ret	0
main	ENDP
_TEXT	ENDS
END
